sylius_payment:
    gateways:
        monext: Monext

winzou_state_machine:
    sylius_order_shipping:
        callbacks:
            after:
                monext_shipping_processor:
                    on:   ['ship']
                    do:   ['@MonextSyliusPlugin\Winzou\ShippingProcessor', 'process']
                    args: ['object', 'event']
    sylius_payment:
        callbacks:
            before:
                monext_complete_processor:
                    on:   ['complete']
                    do:   ['@MonextSyliusPlugin\Winzou\PaymentProcessor', 'complete']
                    args: ['object']
                monext_cancel_processor:
                    on:   ['cancel']
                    do:   ['@MonextSyliusPlugin\Winzou\PaymentProcessor', 'cancel']
                    args: ['object']
                monext_refuns_processor:
                    on:   ['refund']
                    do:   ['@MonextSyliusPlugin\Winzou\PaymentProcessor', 'refund']
                    args: ['object']

sylius_ui:
    events:
        sylius.shop.checkout.header:
            blocks:
                after_legacy:
                    template: "@MonextSyliusPlugin/Action/_widgetResources.html.twig"
