services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    MonextSyliusPlugin\:
        resource: '../../'
        exclude: '../../{Resources, DependencyInjection, MonextSyliusPlugin.php}'
    
    Sylius\Component\Resource\Metadata\MetadataInterface:
        factory: ['@sylius.resource_registry', 'get']
        arguments: ['sylius.order']
    
    sylius.controller.payum:
        alias: MonextSyliusPlugin\Payum\Controller\PayumController

    GuzzleHttp\Client: ~
    
    monext_sylius_plugin.gateway_factory.monext:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        tags:
            - { name: 'payum.gateway_factory_builder', factory: 'monext' }
        arguments:
            - 'MonextSyliusPlugin\Payum\MonextGatewayFactory'
    
    MonextSyliusPlugin\Helpers\MonextPayloadHelper:
        arguments:
            $localNotifyHost: '%env(default::LOCAL_NOTIFY_HOST)%'
        
    MonextSyliusPlugin\Form\Type\MonextGatewayConfigurationType:
        tags:
            - { name: 'sylius.gateway_configuration_type', type: 'monext', label: 'Monext' }

    MonextSyliusPlugin\Payum\Action\CaptureAction:
        tags:
            - { name: 'payum.action', factory: 'monext', prepend: true, alias: 'payum.action.capture'}

    MonextSyliusPlugin\Payum\Action\NotifyAction:
        tags:
            - { name: 'payum.action', factory: 'monext', prepend: true, alias: 'payum.action.notify'}

    MonextSyliusPlugin\Payum\Action\AuthorizeAction:
        tags:
            - { name: 'payum.action', factory: 'monext', prepend: true, alias: 'payum.action.authorize'}

    MonextSyliusPlugin\Payum\Action\GetStatusAction:
        tags:
            - { name: 'payum.action', factory: 'monext', prepend: true, alias: 'payum.action.status'}

    MonextSyliusPlugin\Payum\Action\CancelAction:
        tags:
            - { name: 'payum.action', factory: 'monext', prepend: true, alias: 'payum.action.cancel'}

    MonextSyliusPlugin\Payum\Action\RefundAction:
        tags:
            - { name: 'payum.action', factory: 'monext', prepend: true, alias: 'payum.action.refund'}
